name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-and-push
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker image names
        id: vars
        run: |
          IMAGE_BASE=ghcr.io/${{ github.repository_owner }}/subdownloader
          IMAGE_LATEST=${IMAGE_BASE}:latest
          IMAGE_SHA=${IMAGE_BASE}:sha-${GITHUB_SHA}
          echo "image_latest=${IMAGE_LATEST,,}" >> $GITHUB_OUTPUT
          echo "image_sha=${IMAGE_SHA,,}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.vars.outputs.image_latest }}
            ${{ steps.vars.outputs.image_sha }}
          platforms: linux/amd64,linux/arm64
